# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Resumify"
license = "MIT"
licenselink = "https://github.com/juhi-trivedi/hugo-resumify/blob/master/LICENSE"
description = "A responsive landing page created using Hugo."
homepage = "https://hugo-resumify.netlify.com/"
tags = ['landing-page', 'business', 'agency-template', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages']
features = ['bootstrap','responsive']
min_version = "0.41"

[author]
  name = "Juhi Trivedi"
  homepage = "https://hugo-resumify.netlify.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
